"""Add encryption for API keys

Revision ID: b1ffb232a162
Revises: eb0bf5c3a789
Create Date: 2025-08-24 20:48:40.197977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1ffb232a162'
down_revision: Union[str, None] = 'eb0bf5c3a789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
